#!/usr/bin/env python

import rospy

import cv2
from cv_bridge import CvBridge, CvBridgeError

from sensor_msgs.msg import Image

import baxter_interface
from baxter_interface import CHECK_VERSION

class Camtest(object):
    def __init__(self):
	self.sub = rospy.Subscriber('/cameras/right_hand_camera/image', Image, self.callback)
	self.bridge = CvBridge()

    def callback(self, msg):
	try:
	    self.img = self.bridge.imgmsg_to_cv2(msg)
	    cv2.imshow("Right", self.img)
	    cv2.waitKey(1)
	except CvBridgeError as e:
	    print("Bridge-Error")
	    
def main():
    print("Initializing node... ")
    rospy.init_node("camtest")

    camtest = Camtest()
    
    rospy.spin()
    print("Finished")

if __name__ == '__main__':
    main()
